### ISSUE TITLE
Permitir seleccionar varios operadores en los reportes de impresión 

### ISSUE THREAD

**Issue by jcastell91** [AxisPOS/AxisPOSIssues#20]
Actualmente los reportes de impresión(circulación, ventas x mercancías, etc) solo permite imprimir las ventas de todos los operadores o de uno. Sería interesante permitir la selección de varios de ellos.

**Comment by jkarpio** [comment]
Los reportes de turno son por el usuario qué abrió el turno, el reporte de circulación sale por operadores estos reportes se encuentra en el menú reportes del restaurante y tienda
